workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /^Merge/'
      when: always
    - when: never

stages:
  - test
  - build

unit_tests:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - cd liquibase-migration-application
    - cd library-application-system

build:
  stage: build
  script:
    - echo "Pipeline triggered after merge request to main"